FROM php:8.2-apache
RUN docker-php-ext-install pdo pdo_mysql
RUN a2enmod headers rewrite

COPY api/ /var/www/html/api/
COPY uploads/ /var/www/html/uploads/

RUN chown -R www-data:www-data /var/www/html/uploads

EXPOSE 80
